### ISSUE TITLE
ZeligMultilevel: zeligPlyrMutate breaking all models

### ISSUE THREAD

**Issue by tercer** [IQSS/Zelig#252] opened 2017-04-12 22:47 UTC
All the Multilevel models are breaking because zeligPlyrMutate has gone.

<img width="873" alt="screen shot 2017-04-12 at 6 40 26 pm" src="https://cloud.githubusercontent.com/assets/2085037/24982576/0b351f56-1fb0-11e7-87f5-3acc812e3129.png">

This is likely just the name change in #175 creating the same issue as seen in #187 

I realize this package is under development, but when it breaks the docs on zeligproject.org, it breaks docs that follow in strange ways. For now, I've set EVAL=FALSE for all Multilevel models on the docs. It might make sense to remove them until we have a Multilevel package that is released.

**Comment by christophergandrud** [comment] 2017-04-13 05:15
Agreed on removing models from the docs before they are released.

**Comment by christophergandrud** [comment] 2017-04-18 12:57
Resolving the `ZeligPlyrMutate` issue may have created the `sim` issue. 

When `ZeligMultilevel` is build the following warning produced is: 

```
Warning: replacing previous import ‘Zelig::sim’ by ‘arm::sim’ when loading ‘ZeligMultilevel’
```

So the errors in https://github.com/IQSS/Zelig/issues/253 could be caused by `arm::sim` not being able to find a way to handle the Zelig object.

**Comment by christophergandrud** [comment] 2017-04-18 13:47
Turns out the `sim` import issue was it. 

I set `eval=FALSE` for all code chunks in the docs with `library(ZeligMultilevel)` and the `sim` error went away. https://github.com/IQSS/docs.zeligproject.org/commit/b2e1582b4f93c8984e287d6174434b3e1fe7746b

E.g.: http://docs.zeligproject.org/en/latest/zelig-quantile.html

**Comment by christophergandrud** [comment] 2017-04-18 13:48
We need to set it back to `eval=TRUE`, eventually, but my understanding is that ZeligMultilevel is being completely rewritten without **arm** is that correct @cchoirat?

**Closed by christophergandrud** 2017-04-18 13:47 UTC
