### ISSUE TITLE
Using bs() from library(splines) with setx()

### ISSUE THREAD

**Issue by ewanedwards** [IQSS/Zelig#218] opened 2017-02-14 16:30 UTC
Hi there, I tweeted about this a couple of weeks ago. I'm a total Github n00b so please be patient!

I would like to run GEEs using bs() from the splines package to generate smoothed relationships i.e. GEE-GAMs as opposed to GEE-GLMs. I am modelling ecological binary (presence/absence) data using binomial GEEs to account for inherent autocorrelation within blocks of data.

The main appeal of your package is being able to generate confidence limits in a straightforward manner, using setx(). But this doesn't seem to work with my bs(covariates) - even though the models do run. Would this be a feature you could develop into the package?

Many thanks,
Ewan

**Comment by christophergandrud** [comment] 2017-02-14 16:34
Hi @ewanedwards. Thanks for reporting this on GitHub.

I think the issue is related to https://github.com/IQSS/Zelig/issues/199 which I'm planning on addressing in the near future.

To help me out. Could you give a minimal reproducible example of the model you would like to estimate?

**Comment by ewanedwards** [comment] 2017-02-14 16:39
Thanks for replying Christopher.

My model is like this:

z.out <- zelig(pres_abs ~ bs(depth, knots=mean(depth)) + bs(slope, knots=mean(slope)) + bs(distance, knots=mean(distance)), model="logit.gee", id = "location", data = dat, corstr = "ar1")

where:
pres_abs is a binary variable indicating presence or absence
depth, slope and distance are continuous variables (greater than 0)

**Comment by christophergandrud** [comment] 2017-03-08 12:55
The current dev version downloadable from GitHub (`devtools::install_github('IQSS/Zelig')` should be able to get you what you want. Though currently you need to create the splines *outside of* the `zelig` call.

Here is a silly example:

```r
library(Zelig)
library(dplyr)
library(splines)

# Create splines
cars.splines <- cbind(cars, bs(cars$dist))
names(cars.splines)[3:5] <- c('dist_bs_1', 'dist_bs_2', 'dist_bs_3')

zelig(speed ~ dist_bs_1 + dist_bs_2 + dist_bs_3, data = cars.splines, 
      model = 'ls', cite = FALSE) %>%
    setx(dist_bs_1 = c(min(cars.splines$dist_bs_1), median(cars.splines$dist_bs_1), 
                       max(cars.splines$dist_bs_2)),
         dist_bs_2 = c(min(cars.splines$dist_bs_2), median(cars.splines$dist_bs_2), 
                       max(cars.splines$dist_bs_2)),
         dist_bs_3 = c(min(cars.splines$dist_bs_3), median(cars.splines$dist_bs_3), 
                       max(cars.splines$dist_bs_3))) %>%
    sim() %>%
    plot()
```

**Comment by christophergandrud** [comment] 2017-03-08 12:56
I'm going to close this issue for now, but hope to have the fully implemented syntax you propose in a future Zelig version.

**Closed by christophergandrud** 2017-03-08 12:56 UTC
Labels: type: feature
